### ISSUE TITLE
Calendar Feeds always list sub requests...

### ISSUE THREAD

**Issue by caseywatts** [YaleSTC/shifts#223] opened 2014-03-04 00:57 UTC
...even when they haven't been sub requested.

Line 98 has a sub request conditional that should also be applied to line 99.
https://github.com/YaleSTC/shifts/blob/rails-3.2/app/controllers/calendar_feeds_controller.rb#L99

**Comment by orenyk** [comment] 2015-01-22 00:32
This has been noted again by one of our clients, we should try and patch it so it will be fixed when they update to Shifts 3.

**Comment by njlxyaoxinwei** [comment] 2015-01-30 02:13
The problem is fixed for Shifts2 by [this commit](https://github.com/YaleSTC/shifts/commit/61584eec56eab4760dcaf531cbfb733c0b8d5206). However, calendar feeds do not work at all on Shifts3, so when we fix that we should cherry-pick the change into Shifts3. See issue #419

**Closed** 2015-01-30 02:18 UTC
